### ISSUE TITLE
The Hotkey is not working on MacbookPro M1

### ISSUE THREAD

**Issue by RTX7777Ti** [swift-project/pilotclient#197]
I set a PTT Button to Right Option key but it's doesn't work.The ”PTT“ is not light-up.
PS:I'm using the macbook pro m1, macos ventura, x-plane11, swift 0.12.92.And I also connected to the VATSIM before.

**Comment by esramos-design** [comment]
I believe most this errors should be fixed to turn ON/OFF/ON the mic and all items of swift , it MUST shows up the pop up to accept on the first time

**Comment by esramos-design** [comment]
there's a comment pinned in mac channel

Thomaz11 — 23/10/2020 22:38
Ooops, as for PTT it WORKS!! To assign a key from your keyboard just make sure you go into the privacy in system preferences and make sure INPUT MONITORING is allowed in Swift Gui.

**Comment by esramos-design** [comment]
and these i have been telling all showed screenshots https://discord.com/channels/539048679160676382/567983892791951374/1054660389524213811

**Comment by RTX7777Ti** [comment]
> there's a comment pinned in mac channel
> 
> Thomaz11 — 23/10/2020 22:38 Ooops, as for PTT it WORKS!! To assign a key from your keyboard just make sure you go into the privacy in system preferences and make sure INPUT MONITORING is allowed in Swift Gui.

I've already allowed the Swift permissions but it's still doesn't work.like before.
So, here is the photo:
[https://imgloc.com/i/MlSbL](https://imgloc.com/i/MlSbL)

**Comment by ltoenning** [comment]
No update since a month. I will close it for now as I cannot reproduce this and I am not aware of other users reporting this issue.

@RTX7777Ti If the issue still persists, feel free to reopen it.
